# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Elixir 1.18 with OTP 28 by mise
      uses: jdx/mise-action@v2.2.2
      with:
        mise_toml: |
          [tools]
          erlang = '28.0'
          elixir = '1.18.4'
    #- name: Set up Elixir 1.18 with OTP 28
    #  uses: erlef/setup-beam@cc72a5b176d1973f6c4326e756645266650ddccb
    #  with:
    #    elixir-version: '1.18.4'
    #    otp-version: '28.0'
    - name: Install dependencies (Elixir 1.18 with OTP 28)
      run: mix deps.get
    - name: Check format (Elixir 1.18 with OTP 28)
      run: mix format --check-formatted --migrate
    - name: Check by the new type system (Elixir 1.18 with OTP 28)
      run: mix compile --all-warnings --warnings-as-errors --no-compile
    - name: Run tests (Elixir 1.18 with OTP 28)
      run: mix test

    - name: Set up Elixir 1.17 with OTP 27
      uses: erlef/setup-beam@cc72a5b176d1973f6c4326e756645266650ddccb
      with:
        elixir-version: '1.17.3'
        otp-version: '27.3.4'
    - name: Install dependencies (Elixir 1.17 with OTP 27)
      run: mix deps.get
    - name: Run tests (Elixir 1.17 with OTP 27)
      run: mix test

    - name: Set up Elixir 1.16 with OTP 26
      uses: erlef/setup-beam@cc72a5b176d1973f6c4326e756645266650ddccb
      with:
        elixir-version: '1.16.3'
        otp-version: '26.2.5.12'
    - name: Install dependencies (Elixir 1.16 with OTP 26)
      run: mix deps.get
    - name: Run tests (Elixir 1.16 with OTP 26)
      run: mix test

    - name: Set up Elixir 1.15 with OTP 25
      uses: erlef/setup-beam@cc72a5b176d1973f6c4326e756645266650ddccb
      with:
        elixir-version: '1.15.8'
        otp-version: '25.3.2.21'
    - name: Install dependencies (Elixir 1.15 with OTP 25)
      run: mix deps.get
    - name: Run tests (Elixir 1.15 with OTP 25)
      run: mix test

